export const  passwordManagerTypes = {
    ACCEPT_CONDITIONS:'ACCEPT_CONDITIONS',
    CHANGE_VALUES:'CHANGE_VALUES',
    CHANGE_STEP:'CHANGE_STEP',
    CHANGE_TO_NEXT_STEP:'CHANGE_TO_NEXT_STEP',
    CHANGE_TO_PREVIOUS_STEP:'CHANGE_TO_PREVIOUS_STEP',
    CHANGE_FULL_STEP_SUCCEEDED:'CHANGE_FULL_STEP_SUCCEEDED',
    RESET_STATE:'RESET_STATE',
    LOADING:'LOADING',
}